version: "3.8"

services:
  api:
    build: .
    container_name: freshly-api
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/freshly_supermarket
      - SECRET_KEY=your-secret-key-change-in-production
      - ENVIRONMENT=development
    labels:
      - traefik.enable=true
      - "traefik.docker.network=traefik-public"
      - traefik.http.routers.freshly-api-http.rule=Host(`freshlyapi.kevinlinportfolio.com`)
      - traefik.http.routers.freshly-api-http.entrypoints=http
      - traefik.http.routers.freshly-api-http.middlewares=https-redirect
      - traefik.http.routers.freshly-api-https.rule=Host(`freshlyapi.kevinlinportfolio.com`)
      - traefik.http.routers.freshly-api-https.entrypoints=https
      - traefik.http.routers.freshly-api-https.tls=true
      - traefik.http.routers.freshly-api-https.tls.certresolver=le
      - traefik.http.routers.freshly-api-https.service=freshly-api-service
      - traefik.http.services.freshly-api-service.loadbalancer.server.port=8000
    networks:
      - traefik-public
      - default

  db:
    image: postgres:14
    container_name: freshly-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=freshly_supermarket
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    container_name: freshly-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@freshly.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - "traefik.docker.network=traefik-public"
      - traefik.http.routers.pgadmin-http.rule=Host(`pgadmin.freshlyapi.kevinlinportfolio.com`)
      - traefik.http.routers.pgadmin-http.entrypoints=http
      - traefik.http.routers.pgadmin-http.middlewares=https-redirect
      - traefik.http.routers.pgadmin-https.rule=Host(`pgadmin.freshlyapi.kevinlinportfolio.com`)
      - traefik.http.routers.pgadmin-https.entrypoints=https
      - traefik.http.routers.pgadmin-https.tls=true
      - traefik.http.routers.pgadmin-https.tls.certresolver=le
      - traefik.http.routers.pgadmin-https.service=pgadmin-service
      - traefik.http.services.pgadmin-service.loadbalancer.server.port=80
      - traefik.http.middlewares.pgadmin-auth.basicauth.users=admin:$$apr1$$byxbdi2b$$7TVE23kherHkJrbKnEzMm1



      

volumes:
  postgres_data:
  pgadmin_data:

networks:
  traefik-public:
    external: true
  default:
